databases:
  - name: SpySpace
    databaseName: spyspace
    user: zakschenck

services:
  - type: web
    name: SpySpace
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: SpySpace
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false