default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: zakschenck
  password: <%= ENV['SPYSPACE_DATABASE_PASSWORD'] %>
  host: localhost

development:
  <<: *default
  database: spyspace

# test:
#   <<: *default
#   database: your_app_test

production:
  <<: *default
  DATABASE_URL: "postgresql://zakschenck:Z@k5ch3nck1!@localhost:5432/spyspace"